### PR TITLE
Fix some issues with update script

### PR DESCRIPTION
**Pull request by mattstratton**

### CODE REVIEW

**Comment by mattstratton** [comment]
You can take this PR, but do NOT run this script; it's not working in general.

**Comment by mattstratton** [comment]
OK, this script will work now...I think :)

**Comment by mary-grace** [comment]
@mattstratton I just realized this PR is still open 😬 Is there anything I should be aware of that may have changed since (yikes) Nov 29, 2019? 😅

**Comment by mattstratton** [comment]
The script should work - I’ve been using it on two other podcasts. 

There is a relatively major update to castanet which you might want to consider - it updates the audio player and also fixes some minor iTunes feed tags :)

**Comment by mary-grace** [comment]
@mattstratton Fantastic! Thanks for the heads-up. I thought I was up-to-date on all of the major releases but I'll be sure to pull that one over today.

**Comment by mattstratton** [comment]
@mary-grace yeah 1.2 came out about 10 days ago :)

**Comment by mary-grace** [comment]
oh yay!! congrats 😁 I'll definitely pull that in this morning.

**Pull request merged**
