### PR TITLE
Update castanet version

### PR DESCRIPTION
**Pull request by mattstratton**
This change updates the theme to work properly with hugo 0.58 and above. It also updates the version of hugo used by netlify on this repo.

### CODE REVIEW

**Comment by mattstratton** [comment]
Okay, so I noticed something wacky...your version of `bin/netlify-production.sh` is referring to the "community-pulse" theme and not "castanet". Did you pivot from castanet?

**Comment by mattstratton** [comment]
Actually it looks like it's been wrong all along; so I am wondering if we never actually moved you to castanet?

**Comment by mattstratton** [comment]
Yeah, this is in a weird place. `bin/netlify-production.sh` needs to be updated.

**Comment by mattstratton** [comment]
It seems like it's ignoring the theme flag and building based on what's in the config.toml though; you clearly *are* running Castanet in prod. So strange.

**Comment by mattstratton** [comment]
I've updated this PR with a few changes; I added the bit to the build script (which I don't know why it was already working, but whatever), and also there have been a couple small castanet updates since the original PR, so I added those.

**Comment by mary-grace** [comment]
You're amazing -- thanks, Matt! I really appreciate it.

**Pull request merged**
